version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
        #      TZ: America/Sao_Paulo
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

