version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
        #      TZ: America/Sao_Paulo
    volumes:
      - db_data:/var/lib/mysql
  web:
    build:
      context: ./web
    container_name: django-web
    ports:
      - "8000:8000"
    volumes:
      - ./web:/app
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_NAME: mydb
      DATABASE_USER: myuser
      DATABASE_PASSWORD: mypassword
    depends_on:
      - db

volumes:
  db_data:

